alias: "EVCC: Morgendlicher reset von Battery Grid Charge Limit"
description: ""
triggers:
  - trigger: time
    at: "09:00:00"
conditions: []
actions:
  - action: number.set_value
    metadata: {}
    data:
      value: "0"
    target:
      entity_id: number.evcc_site_battery_grid_charge_limit
mode: single