alias: "Heimspeicher: Nächtliches Speichersparen morgens beenden"
description: ""
triggers:
  - alias: Morgens um 6:30
    trigger: time
    at: "06:00:00"
conditions:
  - condition: state
    entity_id: input_boolean.helper_nightly_battery_saver
    state: "on"
    alias: Wenn nächtliches Speichersparen aktiviert wurde.
actions:
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.helper_nightly_battery_saver
    data: {}
    alias: Flag löschen
  - action: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.helper_home_battery_discharge_disabled
    alias: Speicher aktivieren
mode: single
