alias: "Heimspeicher: Nächtliches Speichersparen aktivieren"
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.sofar_battery_capacity_total
    below: 35
  - trigger: time
    at: "00:00:00"
conditions:
  - alias: Zwischen 0:00 und 6:30
    condition: time
    after: "00:00:00"
    before: "06:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  - condition: numeric_state
    entity_id: sensor.sofar_battery_capacity_total
    below: 35
actions:
  - alias: Speicherentladung deaktiviert
    action: input_boolean.turn_on
    target:
      entity_id:
        - input_boolean.helper_home_battery_discharge_disabled
        - input_boolean.helper_nightly_battery_saver
    data: {}
mode: single
