alias: Speicherentladung deaktiveren
description: >-
  Deaktiviert die Entladung der Speicher Batterie, wenn der Helfer auf An
  geschaltet wird.
trigger:
  - platform: state
    entity_id:
      - input_boolean.helper_home_battery_discharge_disabled
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 5
condition: []
action:
  - alias: Passive Mode setzen
    continue_on_error: true
    target:
      entity_id:
        - select.sofar_charger_use_mode
    data:
      option: Passive Mode
    action: select.select_option
  - alias: Entladeleistung auf 0 setzen
    target:
      entity_id:
        - number.sofar_passive_mode_battery_power_min
    data:
      value: "0.0"
    action: number.set_value
  - alias: Batterieleistung setzen
    continue_on_error: true
    target:
      entity_id:
        - button.sofar_passive_mode_battery_charge_discharge
    data: {}
    action: button.press
mode: single
