alias: "iGo: Helper aus: Smartes Laden ausschalten"
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_boolean.helper_intelligent_go
    from: "on"
    to: "off"
    alias: "'Intelligent Go' Helper wird in Home Assistant ausgeschaltet"
conditions: []
actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.octopus_a_<octopus_id>_device_smart_control
    alias: Smartes Laden bei Octopus deaktivieren
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - alias: Überprüfe ob Smart Laden wirklich ausgeschaltet wurde.
    if:
      - condition: not
        conditions:
          - condition: state
            entity_id: switch.octopus_a_<octopus_id>_device_smart_control
            state: "off"
    then:
      - alias: Sende eine Benachrichtigung an die Companion App
        action: notify.mobile_app_<companion_app_device_name>
        metadata: {}
        data:
          title: "iGo: Smart Laden konnte nicht ausgeschaltet werden."
          message: >-
            Es ist etwas schief gelaufen. Smart Laden konnte nicht ausgeschaltet
            werden.
          data:
            notification_icon: mdi:car-electric
            color: red
mode: single
