alias: "LP2: iGo: EVCC auf 'Schnell': Sofort starten"
description: ""
triggers:
  - trigger: state
    entity_id:
      - select.evcc_lp_1_mode
    to: now
    alias: Der Lademodus des Ladepunktes wird auf 'Schnell' geschaltet.
conditions:
  - alias: >-
      'Intelligent Go" Helfer ist aus oder tagsüber (nachts bei aktiviertem
      Smarten Laden laufen wir in Konflikt mit Intelligent Go)
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.helper_intelligent_go
        state: "off"
      - condition: sun
        before: sunset
        after: sunrise
actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.octopus_a_<octopus_id>_device_smart_control
    alias: >-
      Sicherstellen, dass Smartes Laden bei Octopus aus ist und uns nicht
      dazwischenpfuscht.
  - action: script.tesla_ladevorgang_starten
    metadata: {}
    data: {}
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - alias: Überprüfe ob Smart Laden wirklich ausgeschaltet wurde.
    if:
      - condition: not
        conditions:
          - condition: state
            entity_id: switch.octopus_a_<octopus_id>_device_smart_control
            state: "off"
    then:
      - alias: Sende eine Benachrichtigung an die Companion App
        action: notify.mobile_app_<companion_app_device_name>
        metadata: {}
        data:
          title: "iGo: Smart Laden konnte nicht ausgeschaltet werden."
          message: >-
            Es ist etwas schief gelaufen. Smart Laden konnte nicht ausgeschaltet
            werden.
          data:
            notification_icon: mdi:car-electric
            color: red
mode: single
