alias: "LP1: iGo: EVCC auf 'Schnell': Sofort starten"
description: ""
triggers:
  - trigger: state
    entity_id:
      - select.evcc_lp_1_mode
    to: now
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.helper_lp1_octopus_intelligent_go_active
        state: "off"
      - condition: state
        entity_id: sensor.octopus_intelligent_dispatching_a_<octopus_kunden_nummer>
        state: "off"
    alias: Intelligent Go ist aus oder ausserhalb der Intelligent Go Zeit
actions:
  - action: script.tesla_ladevorgang_starten
    metadata: {}
    data: {}
mode: single
