alias: "LP2: iGo: Sonstige Zeit: Überprüfe ob Ladevorgang gestartet wurde"
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.evcc_lp_2_enabled
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 3
      seconds: 0
conditions:
  - condition: state
    entity_id: binary_sensor.evcc_lp_2_connected
    state: "on"
  - condition: or
    conditions:
      - condition: state
        entity_id: select.evcc_lp_2_mode
        state: pv
      - condition: state
        entity_id: select.evcc_lp_2_mode
        state: now
    alias: mode ist pv oder now
  - condition: state
    entity_id: binary_sensor.evcc_lp_2_charging
    state: "off"
  - alias: Intelligent Go ist aus oder ausserhalb der Intelligent Go Zeit
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.helper_lp2_octopus_intelligent_go_active
        state: "off"
      - condition: state
        entity_id: sensor.octopus_intelligent_dispatching_a_<octopus_kunden_nummer>
        state: "off"
actions:
  - action: script.tesla_ladevorgang_starten
    metadata: {}
    data: {}
  - action: notify.mobile_app_<companion_app_device_name>
    metadata: {}
    data:
      title: "iGo: Ladevorgang nicht gestartet"
      message: >-
        Der Ladevorgang ist nicht automatisch gestartet. Wurde nochmals im Tesla
        gestartet.
      data:
        notification_icon: mdi:car-electric
        tag: igo-charging
mode: single
