alias: "Heimspeicher: Manuelle Ladung abgeschlossen"
description: ""
triggers:
  - entity_id:
      - sensor.sofar_battery_capacity_total
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: 80
    trigger: numeric_state
conditions:
  - condition: state
    entity_id: input_boolean.helper_home_battery_manual_charging
    state: "on"
actions:
  - data: {}
    target:
      entity_id: input_boolean.helper_home_battery_manual_charging
    action: input_boolean.turn_off
  - data:
      title: Heimspeicher voll.
      message: Manuelles Laden des Heimspeichers abgeschlossen.
    action: notify.ntfy_info
mode: single
